### ISSUE TITLE
你好,dlj.biz能否让我加入bingher/surl的驱动?

### ISSUE THREAD

**Issue by hbh112233abc** [LunziSTU/dlj.biz-php#1]
你好,请问你是dlj.biz站点的作者么?
我也做了一个短链接扩展bingher/short-url(https://github.com/hbh112233abc/short-url)
现在对接了百度和新浪,以驱动的形式增加对其他站点的接口的支持,请问能否把你的dlj.biz接口也加入进来呢?
可以的话,我就发版本了:)

**Comment by LunziSTU** [comment]
你好，可以的，感谢支持！

**Comment by LunziSTU** [comment]
你好，可以的，感谢支持！

**Comment by hbh112233abc** [comment]
谢谢 我是从thinkphp周刊看到推荐你的扩展哦 赞
